<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
    <section class="question custom">
        <p>What is your daily calorie intake?</p>

        <p>
            <input type="number" step="0.01" min="0" placeholder="Fill the price here" name="answer[<?= $fact ?>]" /> kCal
        </p>

        <ol class="options">
            <li class="single-click">
                <button type="submit">Submit</button>
            </li>
            <li class="single-click">
                <button type="submit" name="answer[<?= $fact ?>]" value="undefined">I have no caloric restrictions on my diet</button>
            </li>
        </ol>

    </section>
<?php $this->end() ?>