<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<div class="block-center">
    <?php if(count($products) > 0): ?>
    <table class="product-table" border="0" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th class="numeric">Price (&euro;)</th>
                <th class="numeric">Sugar (g)</th>
                <th class="numeric">Calories (kCal)</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($products as $product): ?>
            <tr>
                <td><img class="product-image" src="/<?= $product['image'] ?>" alt="" /></td>
                <td><?= $product['name'] ?></td>
                <td class="numeric">&euro; <?= number_format($product['price'], 2, '.', '') ?></td>
                <td class="numeric"><?= $product['sugar'] ?></td>
                <td class="numeric"><?= $product['calories'] ?></td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php else: ?>
    <p>There are no products that match your preferences</p>
    <?php endif ?>
</div>
<?php $this->end() ?>